### PR TITLE
Update Builder.cs

### PR DESCRIPTION
**Pull request by LocalSmail**
added randomization for len

### CODE REVIEW

**Comment by Blank-c** [comment]
Shouldn't the key and iv be 32 bytes and 12 bytes?

**Comment by LocalSmail** [comment]
> Shouldn't the key and iv be 32 bytes and 12 bytes?

It can be

**Comment by LocalSmail** [comment]
Just the lower the less secure it would be

**Comment by Blank-c** [comment]
Sorry but I don't see any advantage of it. If someone can already see the encrypted data, key and iv, then increasing its length would not provide any additional security.

**Comment by Blank-c** [comment]
> > Sorry but I don't see any advantage of it. If someone can already see the encrypted data, key and iv, then increasing its length would not provide any additional security.
> 
> It just helps with brute forcing. If the receiver can view the key and iv anyway then it's a massive flaw.

I don't think someone would be this naive to try to bruteforce the iv and key for a mere encrypted webhook to decrypt it.

Besides, the key and iv are stored along with the webhook. If someone can access the encrypted webhook, they can also access the iv and key.

**Comment by Blank-c** [comment]
I think it require better obfuscation instead of mangling keys and iv.

Besides, I am pretty new to C# and I don't know how to make a custom obfuscator :P

**Comment by Resisst** [comment]
> added randomization for len

bro wtf is this pr
the standard for aes-gcm is a 12 byte nonce and a 16/32 byte key

?!??!!

**Pull request closed without merging**
